---
- name: Download providence
  hosts: all
  vars:
    providence_collector_url: "{{ lookup('env','PROVIDENCE_COLLECTOR_DOWNLOAD_URL') | default('', true) }}"
    providence_install_dir: /home/pi/tools/providence-collector
  tasks:
    - name: "Download"
      shell: 'wget -c {{ providence_collector_url }} -O /tmp/providence-collector.tar.gz'
    - name: "Remove old providence"
      shell: 'rm -rf {{ providence_install_dir }}'
    - name: "Create install dir"
      shell: 'mkdir -p {{ providence_install_dir }}'
    - name: "Extract"
      shell: 'tar --strip-components=1 -xvf /tmp/providence-collector.tar.gz -C {{ providence_install_dir }}'
    - name: "Restart"
      shell: '{{ providence_install_dir }}/bin/providence-collector-service restart'
    - name: "Cleanup"
      shell: 'rm /tmp/providence-collector.tar.gz'